# Generated by Django 6.0.4 on 2026-05-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='banner',
            field=models.ImageField(blank=True, default='lambo.webp', upload_to=''),
        ),
    ]
