# Generated by Django 6.0.4 on 2026-06-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
