# Generated by Django 6.0.4 on 2026-06-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('northland', 'Northland'), ('auckland', 'Auckland'), ('waikato', 'Waikato'), ('bay_of_plenty', 'Bay Of Plenty'), ('gisborne', 'Gisborne'), ('hawkes_bay', "Hawke's Bay"), ('taranaki', 'Taranaki'), ('manawatu_whanganui', 'Manawatū-Whanganui'), ('wellington', 'Wellington'), ('tasman', 'Tasman'), ('nelson', 'Nelson'), ('marlborough', 'Marlborough'), ('west_coast', 'West Coast'), ('canterbury', 'Canterbury'), ('otago', 'Otago'), ('southland', 'Southland')], null=True),
        ),
    ]
