# Generated by Django 6.0.4 on 2026-06-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_category_alter_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Electronics', 'Electronics'), ('Motors', 'Motors'), ('Fashion', 'Fashion'), ('Art/Music', 'Art/Music'), ('Property', 'Property'), ('Health', 'Health'), ('Other', 'Other')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('Northland', 'Northland'), ('Auckland', 'Auckland'), ('Waikato', 'Waikato'), ('Bay Of Plenty', 'Bay Of Plenty'), ('Gisborne', 'Gisborne'), ("Hawke's Bay", "Hawke's Bay"), ('Taranaki', 'Taranaki'), ('Manawatū-Whanganui', 'Manawatū-Whanganui'), ('Wellington', 'Wellington'), ('Tasman', 'Tasman'), ('Nelson', 'Nelson'), ('Marlborough', 'Marlborough'), ('West Coast', 'West Coast'), ('Canterbury', 'Canterbury'), ('Otago', 'Otago'), ('Southland', 'Southland')], max_length=25, null=True),
        ),
    ]
