# Generated by Django 6.0.4 on 2026-07-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_category_alter_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
